language: cpp

git:
  depth: 1

notifications:
  email: false

matrix:
  matrix: 
  include:
  - os: osx
    osx_image: xcode9.2
    compiler: clang
  - os: linux
    dist: trusty
    group: latest
    sudo: required
    services: docker

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    cd ..
    pwd
    docker run -d --name ubuntu -v $(pwd):/benkuper ubuntu:latest tail -f /dev/null
    docker ps
  else
    gem install xcpretty
    gem install xcpretty-travis-formatter
    pwd
    ls -d */
    cd /Users/travis
    git clone --depth=1 --branch=develop-local https://github.com/benkuper/JUCE.git JUCE
    cd /Users/travis/build/benkuper
    mkdir "JUCE Modules"
    cd "JUCE Modules"
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_timeline.git juce_timeline
    cd ..
    pwd
    ls -d */
  fi
install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker exec -t ubuntu bash -c "export DEBIAN_FRONTEND=noninteractive;
    uname -a;
    apt-get install software-properties-common
    add-apt-repository ppa:webkit-team/ppa -y;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get update --fix-missing;
    apt-get update -qq;
    echo 'Installing GCC...';
    apt-get install -y g++-7 gcc-7;
    gcc -v;
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90;
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90;
    export CC=/usr/bin/gcc;
    export CXX=/usr/bin/g++;
    echo ${CC};
    echo ${CXX};
    apt-get install -qq git libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libxcomposite-dev mesa-common-dev libasound2-dev freeglut3-dev libcurl4-gnutls-dev+ libasound2-dev libjack-dev libbluetooth-dev libgtk-3-dev libwebkit2gtk-4.0-dev > /dev/null;
    cd ~;
    pwd;
    git clone --depth=1 --branch=develop-local https://github.com/benkuper/JUCE.git JUCE;
    cd /benkuper;
    mkdir 'JUCE Modules';
    cd 'JUCE Modules';
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_sharedtexture.git juce_sharedtexture
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_timeline.git juce_timeline"
  fi
script:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker exec -t ubuntu bash -c "gcc -v;
    cd /benkuper/CrazyDance/Builds/LinuxMakefile;
    make -j 8 CONFIG=Release"
  else
    xcodebuild -project CrazyDance/Builds/MacOSX_CI/CrazyDance.xcodeproj -configuration Release -jobs 8 | xcpretty -f `xcpretty-travis-formatter`
  fi
after_success:
- |-
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir export
    cd export
    docker cp ubuntu:/benkuper/CrazyDance/Builds/LinuxMakefile/build/CrazyDance .
    zip -r CrazyDance-linux-x64-bleedingedge.zip CrazyDance
    curl --verbose --progress-bar --ipv4 --connect-timeout 8 --max-time 120 --retry 128 --ftp-ssl --disable-epsv --ftp-pasv --ftp-create-dirs -T CrazyDance-linux-x64-bleedingedge.zip -u $FTP_USER:$FTP_PASSWORD --insecure ftp://home403871847.1and1-data.host/crazydance/
  else
    cd /Users/travis/build/benkuper/CrazyDance/Builds/MacOSX_CI/build/Release
    ls
    zip -r -y CrazyDance-osx-bleedingedge.zip CrazyDance.app
    curl --ftp-create-dirs -T CrazyDance-osx-bleedingedge.zip -u $FTP_USER:$FTP_PASSWORD --insecure ftp://home403871847.1and1-data.host/crazydance/
  fi
